plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
exclude:
  - '.idea/workspace.xml'
  - '*.iml'
  - 'node_modules/*'
  - 'Gemfile*'
  - 'package*.json'
  - 'src/*'
  - 'assets/scss/*'
  - '/README.md'
include:
  - LICENSE.md
collections:
  guide:
    output: true
    layout: default

show_downloads: false
markdown: kramdown
